#!/usr/bin/env bash
# custom header
# REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://onepiece.fandom.com/wiki/One_Piece_Wiki;\n\t}\n"
# ERRDIR="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
# SRC="/etc/nginx/sites-enabled/default"
# HEADER="\\\n\tadd_header X-Served-By \$HOSTNAME;\n"
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html

echo "Holberton School" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/error404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

printf %s 'server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        error_page 404 /error404.html;
        server_name _;
        
        add_header X-Served-By $hostname;
        
        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
}
' | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
